# Generated by Django 5.0.7 on 2024-07-21 15:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content_post_content1_post_content2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image4'),
        ),
    ]
